### ISSUE TITLE
Dash(Flask) aufsetzen

### ISSUE THREAD

**Issue by cataleya** [valentinrisch/edm#5]
Flask aufsetzen
Datei oder Comment lesen über flask

**Comment by valentinrisch** [comment]
Eine Dash Anwendung wurde in Verbindung mit Flask aufgesetzt. Eine seperate flask Instanz wird erzeugt und der Dash Instanz als argument übergeben. `app = dash.Dash(__name__, server=server, external_stylesheets=external_stylesheets)`. Damit wird die Konfiguration des flask servers, das routing, I/O von dem Layout getrennt. TODO: Config(Database Urls, sql-lite file, etc.)
