### ISSUE TITLE
Datenbank aufsetzen

### ISSUE THREAD

**Issue by cataleya** [valentinrisch/edm#6]
Datenbank aufsetzen
Tabellen aufsetzen

**Comment by valentinrisch** [comment]
im aktuellen Stand wird eine SQL lite datenbank mit dem 1-million-posts dataset von derstandard.at angesprochen. das Schema ist dort vorgegeben. werden wir uns später auf ein eigenes model festlegen, dann wird das schema mittels ORM erstellt.
